Add Val() method.
nikolaydubina/fpmoney pull request #10
Opened 2024-09-02 13:22 UTC by mwuertinger

Usecases:
- Custom serialization / deserialization
- Persisting Amount as two columns in a database

2024-09-02 15:18 UTC, nikolaydubina requested changes
sure, makes sense.

please add test for this though illustrating that this value is multiplied by 100. perhaps Example test is very nice here.

2024-09-02 15:18 UTC, nikolaydubina commented on amount.go
> +
lets use same notation as in fpdecimal. https://github.com/nikolaydubina/fpdecimal/blob/main/fpdecimal.go#L45
```suggestion
func (a Amount) Scaled() int64 { return a.v }

```

2024-09-03 12:59 UTC, mwuertinger commented
Good idea! Added a test.

2024-09-03 13:06 UTC, nikolaydubina commented on amount_test.go
> +}
ah, let's make it an Example. this is something people should know when they reading documentation

```suggestion
func ExampleAmount_Scaled_fractions() {
	v := fpmoney.FromFloat(42.23, fpmoney.EUR)
	fmt.Println(v.Scaled())
	// Output: 4223
}

func ExampleAmount_Scaled_many_fractions() {
	v := fpmoney.FromFloat(17.0, fpmoney.CLF)
	fmt.Println(v.Scaled())
	// Output: 170000
}

func ExampleAmount_Scaled_large() {
	v := fpmoney.FromFloat(8764534896.42, fpmoney.USD)
	fmt.Println(v.Scaled())
	// Output: 876453489642
}
func ExampleAmount_Scaled_whole() {
	v := fpmoney.FromFloat(23.0, fpmoney.EUR)
	fmt.Println(v.Scaled())
	// Output: 2300
}

func ExampleAmount_Scaled_from_scaled() {
	v := fpmoney.FromIntScaled(17, fpmoney.EUR)
	fmt.Println(v.Scaled())
	// Output: 17
}
```

2024-09-03 13:49 UTC, nikolaydubina approved these changes
<img width="515" alt="Screenshot 2024-09-03 at 21 49 37" src="https://github.com/user-attachments/assets/fd2799e1-a1e6-42cf-80cf-be3ba13d606f">

2024-09-03 13:49 UTC, merged